image: php:7.3-cli

variables:
  APP_DOMAIN: $APP_DOMAIN
  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  DB_HOST: $DB_HOST
  DATABASE_URL: $DATABASE_URL

cache:
  paths:
    - vendor/

#services:
    #- name: mysql:5.7
    #  alias: mysql

before_script:
  - apt update -y
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - apt-get install -y libzip-dev zip
  - apt install sqlite3 libsqlite3-dev -y 
  #- apt-get install php7.3-sqlite3 libsqlite3-0 -y #libc6-udeb
  - docker-php-ext-install pdo  pdo_sqlite zip #pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress

stages:
  - test

phpunit-test:
  stage: test
  script:
    - php -d memory_limit=-1
    - php bin/console cache:clear --env=test
    #- php bin/console doctrine:database:drop --if-exists --force --env=test
    #- php bin/console doctrine:database:create --env=test
    #- php bin/console doctrine:migrations:migrate --env=test --no-interaction
    #- php bin/console doctrine:fixture:load --no-interaction --env=test
    - php bin/phpunit --coverage-text --colors=never

behat-test:
  stage: test
  script:
    - echo "I don't know how run behat yet..."

