image: php:7.4-cli

variables:
  APP_DOMAIN: $APP_DOMAIN
  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  DB_HOST: $DB_HOST
  DATABASE_URL: $DATABASE_URL

cache:
  paths:
    - vendor/

services:
    - name: mysql:5.7
      alias: mysql

before_script:
  - apt update -y
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - apt install -y libzip-dev zip
  - docker-php-ext-install pdo pdo_mysql zip
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress


stages:
  - static_analysis
  - test

phpstan:
  stage: static_analysis
  script: 
    - php bin/console cache:clear
    - php bin/phpunit tests/Controller/DefaultControllerTest.php
    - php vendor/bin/phpstan analyse -c phpstan.neon #--no-progress

phpunit-test:
  stage: test
  script:
    - php bin/console cache:clear --env=test
    - php bin/console doctrine:database:drop --if-exists --force --env=test
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:migrations:migrate --env=test --no-interaction
    #- php bin/console doctrine:fixture:load --no-interaction --env=test 
    - php bin/phpunit --coverage-text --colors=never

behat-test:
  stage: test
  script:
    - echo "I don't know how run behat yet..."

