name: Test

on: [push]

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project v2
        uses: actions/checkout@v2
      
      - name: Checkout project v1
        uses: actions/checkout@v1
      
      # GitHub Action for PHPUnit
      - uses: actions/checkout@master
      - uses: nanasess/composer-installer-action@master
      - run: composer install

      - uses: pxgamer/phpunit-action@master
        with:
          # If there isn't a PHPUnit config, specify files or directories to test
          command: tests/Controller/DefaultController.php

      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          configPath: phpstan.neon
          # installComposer: 1
