name: Test

on: [push]

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project v2
        uses: actions/checkout@v2
      
      - name: Checkout project v1
        uses: actions/checkout@v1
      
      # composer-installer-action
      - uses: actions/checkout@master
      - uses: nanasess/composer-installer-action@master
      - run: composer install
      - run: composer require phpunit/phpunit --dev ^9
      - run: php -d memory_limit=-1

      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          configPath: ci-phpstan.neon
          # installComposer: 1
